### ISSUE TITLE
librepo should still be building Python 2 packages until there are no dependent packages

### ISSUE THREAD

**Issue by bowlofeggs** [rpm-software-management/librepo#136]
I noticed that [Python 2 builds were disabled](https://github.com/rpm-software-management/librepo/commit/c670c6bbbc9df3544e961b6e3def004a5535dd9b) recently. There are still packages in Fedora Rawhide that depend on ```python2-librepo``` (for example, Bodhi):

```
$ dnf repoquery --whatrequires python2-librepo                                                                                          
bodhi-server-0:3.10.0-2.fc30.noarch
python2-rpmdeplint-0:1.4-3.fc29.noarch
```

The [Fedora 30 Python 2 change](https://fedoraproject.org/wiki/Changes/Mass_Python_2_Package_Removal) does not say that Python 2 will be dropped in Fedora 30, contrary to the commit message in librepo. It says that leaf packages will be removed. Please revert c670c6bbbc9df3544e961b6e3def004a5535dd9b until librepo is a leaf package.

**Comment by Conan-Kudo** [comment]
@bowlofeggs Both `rpmdeplint` and `bodhi` are Python 3 capable. Why not just switch them over to Python 3 for Fedora 30?

**Comment by bowlofeggs** [comment]
Hi @Conan-Kudo, Bodhi is now Python 3 only in Fedora 30+, but I'm not sure about rpmdeplint (haven't checked it since I filed this issue).

**Comment by Conan-Kudo** [comment]
[`rpmdeplint`'s `setup.py`](https://pagure.io/rpmdeplint/blob/master/f/setup.py) declares it Python 3 compatible, so it _may_ just work?

**Comment by dralley** [comment]
Seems like the answer is yes: https://pagure.io/rpmdeplint/c/2e7b9697ce4589ae75702d2d7861b02b30f74659?branch=master

**Comment by dralley** [comment]
This should probably be closed now regardless, but it looks like rpmdeplint was definitely ported.
