### ISSUE TITLE
undefined reference to pthread_mutex_trylock

### ISSUE THREAD

**Issue by tpgxyz** [rpm-software-management/librepo#157]
BUILDSTDERR: ld: error: /usr/bin/../lib64/gcc/x86_64-openmandriva-linux-gnu/9.1.1/../../../../lib64/libgpg-error.so: undefined reference to pthread_mutex_trylock

More logs here http://file-store.openmandriva.org/api/v1/file_stores/e6d5a891968724301fc78c92c6712623e67a2a60.log?show=true

**Comment by lukash** [comment]
What leads you to think this is a librepo error? It seems your libgpg-error.so has an undefined reference to pthread_mutex_trylock.

**Comment by tpgxyz** [comment]
@lukash strange as libgpg-error does not link to npth

**Comment by lukash** [comment]
I'm not entirely sure how this is supposed to work.

libgpg-error.so is linked against pthreads using weak symbols:
```
$ nm -D /lib64/libgpg-error.so | grep pthread
                 w pthread_cancel
                 w pthread_mutex_destroy
                 w pthread_mutex_init
                 w pthread_mutex_lock
                 w pthread_mutex_trylock
                 w pthread_mutex_unlock
```

That is on Fedora 30, you can check yours. There's some magic detection of pthread support in `librepo/cmake/Modules/FindGpgme.cmake`. I'm not sure how one is supposed to link against pthread with weak symbols.

This works at least for Fedora builds, so something must be different on your system, could you investigate it? Perhaps start by trying to add -lpthread to the linker line if that fixes the error.

**Comment by tpgxyz** [comment]
@lukash adding -lpthread to the ldflags ofcourse works, but this is manual workaround.

Looks like i'll try to dig in gpgme build.

**Comment by lukash** [comment]
FWIW here's a build on F30 that builds fine, also doesn't have the -lpthread flag.

https://paste.fedoraproject.org/paste/rCDs4mYgAdiVyX4X-qYmcw

**Comment by tpgxyz** [comment]
@lukash Looks like something changed with gpgme-1.13.x and that `librepo/cmake/Modules/FindGpgme.cmake` does not work.

**Comment by lukash** [comment]
Oh, well... 400 lines of copy-paste, who would have thunk...

I won't be diving into that anytime soon, especially since `gpgme-1.13.x` isn't even in Rawhide yet, so no easy way to test it. But I assume we'll have to fix it when it eventually hits.

If you wanna give it a go yourself, you're very welcome :slightly_smiling_face:

**Comment by lukash** [comment]
Seems this never hit us or anyone else, so it likely fixed itself. Closing...
