### ISSUE TITLE
Last published cmt 45292f2492f1b6016e50c4e4956717f63b1eed2e failed to build on rawhide

### ISSUE THREAD

**Issue by morucci** [rpm-software-management/librepo#191]
Hi,

I'm maintaining a copr repo of DNF master in the context of an experimentation of Zuul CI. I saw that the last merged commit on librepo 45292f2492f1b6016e50c4e4956717f63b1eed2e failed to build on rawhide. The same commit built on f30 and f31. See https://copr.fedorainfracloud.org/coprs/fbo/dnf-master/build/1346556/
cc @m-blaha

**Comment by morucci** [comment]
As for dnf and libdnf, I'd like to propose https://github.com/rpm-software-management/librepo/pull/192.

**Comment by kontura** [comment]
It looks like your failing build is not necessarily related to the commit you mentioned, looking at the log all the python tests are failing with `gpg.errors.GPGMEError: GPGME: Invalid crypto engine` from a certain point.

Also I just tried building it on rawhide and it work without problems.

**Comment by morucci** [comment]
Thanks, yes it seems it was a rawhide issue. It seems to be fixed now as I see last commits on libdnf for rawhide succeeded https://copr.fedorainfracloud.org/coprs/fbo/dnf-master/builds/
