### ISSUE TITLE
librepo.download_url() does not save/restore fd position.

### ISSUE THREAD

**Issue by zde** [rpm-software-management/librepo#21]
Not a big issue, just confusing:

> > > import os, librepo, tempfile
> > > t = tempfile.TemporaryFile()
> > > librepo.download_url('file:///etc/passwd', t.fileno())
> > > t.read()
> > > ''
> > > t = tempfile.TemporaryFile()
> > > librepo.download_url('file:///etc/passwd', t.fileno())
> > > t.seek
> > > <built-in method seek of file object at 0xb77049c0>
> > > t.seek(0)
> > > t.read()
> > > 'root:x:0:0:root:/root:/bin/bash\nbin:x:1:1:bin:/bin:/sbin/nologin
> > > ...

**Comment by m-blaha** [comment]
The issue has been fixed and is not reproducible any more.
