### ISSUE TITLE
Invalid label when ENABLE_SELINUX is disabled

### ISSUE THREAD

**Issue by yurivict** [rpm-software-management/librepo#292]
[here](https://github.com/rpm-software-management/librepo/blob/master/librepo/gpg_gpgme.c#L135)

Version: 1.17.0

**Comment by jan-kolarik** [comment]
Hello, could you please provide more info about what is the actual problem with the mentioned empty `exit` label in case of `ENABLE_SELINUX` is turned off? I tried compiling the project locally without any issue encountered.

**Comment by yurivict** [comment]
There was some failure that I can't reproduce now.

Thank you for your help!
