### ISSUE TITLE
Upper case xattr incompatible to Amazon S3

### ISSUE THREAD

**Issue by crazymind1337** [rpm-software-management/librepo#326]
Hello

we are currently in the process of migrating our mirror servers to an versioned S3 bucket in kubernetes. With RPM repos we currently have the issue, that on each sync a new versioned RPM file is created. With using `strace` we have found out, that `librepo` uses xattr to set mtime and some file md5/sha256 hashes. 

`librepo` sets an xattr `user.Librepo.checksum.`, but Amazon S3 [1] stores its metadata always in lower case, so the attribute will be converted to `user.librepo.checksum.`. This results in an error on the next sync:

```
fgetxattr(9, "user.Librepo.checksum.mtime", 0x7ffcb473de40, 255) = -1 ENODATA (No data available)
```

After this error the xattr are set again which results in a new version copy of the file even if output of the `dnf reposync` says something like:

```
[SKIPPED] file1.rpm: Already downloaded
[SKIPPED] file2.rpm: Already downloaded
...
```

We also did some manual tests:

Setting the xattr:
```
xattr -w user.Librepo.checksum.mtime 1728288095870000000 test
```

Reading the xattr:
```
xattr -l test
user.librepo.checksum.mtime: 1728288095870000000
```

Is there any technical reason why the string has an upper case character? 

Could this string be changed to a lower case character?

[1] https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html

**Comment by m-blaha** [comment]
I don't think there is a technical reason for it, so I believe it can be changed.
There are two such attributes:

- `user.Librepo.DownloadInProgress` to mark that the file is being downloaded using librepo and the download can be resumed after error,
- and the mentioned `user.Librepo.checksum.*` set of attributes

**Comment by crazymind1337** [comment]
Nice - I am already creating a PR for that. Found those two xattr already ;-)

**Comment by crazymind1337** [comment]
PR created. Is there something else to do?

**Comment by m-blaha** [comment]
Thank you very much for the PR!

**Comment by crazymind1337** [comment]
I don't want to hurry, but can you give an ETA for this to be ready and available for install on RHEL9?

**Comment by m-blaha** [comment]
To get this fix released in RHEL9 - would you mind filing an RHEL project issue in the Jira - https://issues.redhat.com/browse/RHEL . Then the issue can be planned for one of the future RHEL9 releases.

**Comment by crazymind1337** [comment]
Done: https://issues.redhat.com/browse/RHEL-62033

We also tested the update with a manual compilation and installation: No more new version copies. >> fixed.

**Comment by m-blaha** [comment]
Regarding the RHEL issue, it would be much easier to triage and plan if the bug report included a detailed description of the actual issue (for instance, you could copy the title and description from this GitHub issue). A request for a new release is a bit too general. Would you be open to editing or re-creating the issue with more specific details?
