### ISSUE TITLE
Real url used for metadata download

### ISSUE THREAD

**Issue by mluscon** [rpm-software-management/librepo#57]
Could you please make $subj accessible from librepo api?

**Comment by mluscon** [comment]
Could you please make $subj accessible from librepo api?

**Comment by rholy** [comment]
IIUIC, this blocks https://bugzilla.redhat.com/show_bug.cgi?id=1196629

**Comment by m-blaha** [comment]
The referenced bug is already fixed therefore I'm closing the issue.
