### ISSUE TITLE
Provide a script to build just the SRPM

### ISSUE THREAD

**Issue by rholy** [rpm-software-management/librepo#69]
We are moving the part of our continuous integration process (which builds librepo as well) which builds the binary RPMs to Copr. It means that we need to build just the SRPM and pass it to Copr. Building just a SRPM is much faster than building all the RPMs and it does not require the `BuildRequire`s to be installed. It would be nice if you could provide a script or add an option to `utils/make_rpm.sh` which allows one to build just a SRPM.

BTW, it also means that nightly builds of librepo will become available in Copr and that we don't need the `[rpmbuild options]` argument of `utils/make_rpm.sh` anymore.

**Comment by Tojaj** [comment]
I've added new options to the ``make_rpms.sh`` script, see output of ``--help`` option.
