### ISSUE TITLE
Librepo cannot be build in Copr (and potentially other environments)

### ISSUE THREAD

**Issue by rholy** [rpm-software-management/librepo#70]
Apparently, the Copr environment does not support extended file attributes, thus the `test_download_packages_with_resume_02` test fails there, thus the RPM cannot be build there.

Here is one of the failing builds: https://copr-be.cloud.fedoraproject.org/results/rholy/test/fedora-rawhide-x86_64/00113768-librepo/
```
[...]
2: ======================================================================
2: ERROR: test_download_packages_with_resume_02 (tests.test_yum_package_downloading.TestCaseYumPackagesDownloading)
2: ----------------------------------------------------------------------
2: Traceback (most recent call last):
2:   File "/builddir/build/BUILD/librepo/tests/python/tests/test_yum_package_downloading.py", line 688, in test_download_packages_with_resume_02
2:     xattr.setxattr(pkg.local_path, "user.Librepo.DownloadInProgress", "")
2: IOError: [Errno 95] Operation not supported
[...]
```

(the other solution would be to ask Copr maintainers to allow xattrs but I believe that librepo should be buildable even if xattrs are not allowed)

**Comment by rholy** [comment]
BTW, once fixed, librepo nightly builds will be available in [rpmsoftwaremanagement/librepo-nightly-fedora-rawhide](https://copr.fedoraproject.org/coprs/rpmsoftwaremanagement/librepo-nightly-fedora-rawhide/), [rpmsoftwaremanagement/librepo-nightly-fedora-23](https://copr.fedoraproject.org/coprs/rpmsoftwaremanagement/librepo-nightly-fedora-23/) and [rpmsoftwaremanagement/librepo-nightly-fedora-22 ](https://copr.fedoraproject.org/coprs/rpmsoftwaremanagement/librepo-nightly-fedora-22/)

**Comment by Tojaj** [comment]
Closing as fixed by your patch, thanks!

**Comment by rholy** [comment]
Cool, thank you. There are already some librepo builds available in that Copr.
