### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [rpm-software-management/librepo#78]
I would like to point out that identifiers like "[`__LR_DOWNLOADER_H__`](https://github.com/rpm-software-management/librepo/blob/0afa39ccac9b05a16908cfb16e3139395a8c6644/librepo/downloader.h#L21)" and "[`__LR_LIBREPO_H__`](https://github.com/rpm-software-management/librepo/blob/cd46e47ca3a010cc47a2f3a492a0f9633480c153/librepo/librepo.h#L21)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by Tojaj** [comment]
@elfring Hi, thanks for heads up! I'll take look on that.

**Comment by elfring** [comment]
How do you think about to avoid that [this software](https://github.com/rpm-software-management/librepo/blob/ee9567187cae6eb806aeed8ad8a1260fa880e3b5/librepo/handle.h#L21 "Update candidate") [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
