### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [rpm-software-management/librepo#81]
Some parameters (like "[${CURL_INCLUDE_DIR}](https://github.com/rpm-software-management/librepo/blob/fc42cec6e4b5847f891f310efd8569ead75de489/CMakeLists.txt#L57)" and "[${LIB_INSTALL_DIR}](https://github.com/rpm-software-management/librepo/blob/fc42cec6e4b5847f891f310efd8569ead75de489/librepo/CMakeLists.txt#L66)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes.).

**Comment by dmach** [comment]
Yes, we should ideally fix it, but we are not going to do it, because it works now and we need to work on more critical tasks related to dnf5 now.
