### ISSUE TITLE
Python bindings leak string memory

### ISSUE THREAD

**Issue by msimacek** [rpm-software-management/librepo#83]
In `librepo/python/typeconversion.c` there are many occurences of strings being created, but their reference count is not decremented properly.
For example:

``` c
    PyDict_SetItemString(dict, "repomd",
            PyStringOrNone_FromString(repo->repomd));
```

There the refcount is 2 (1 for creation + 1 for adding to dictionary), which causes the object to be leaked after it goes out of scope. It can be seen with valgrind. It should be decremented to 1, like this:

``` c
    PyObject *value = PyStringOrNone_FromString(repo->repomd);
    PyDict_SetItemString(dict, "repomd", value);
    Py_DECREF(value);
```

**Comment by Tojaj** [comment]
Thanks for the bug report!
