### ISSUE TITLE
Allow users to override the CA bundle used by curl

### ISSUE THREAD

**Issue by copumpkin** [rpm-software-management/librepo#85]
I think the "traditional" environment variable is something like `CURL_CA_BUNDLE`, but when you use `curl` programmatically I don't think it pays attention to that. It looks like `librepo` is using `curl_easy_setopt`, and `CURLOPT_CAINFO` is the option needed for that (according to [this page](https://curl.haxx.se/libcurl/c/curl_easy_setopt.html))

**Comment by jrohel** [comment]
The `lr_handle_setopt` function allows to set CA bundle. `LrHandleOption` option is `LRO_SSLCACERT`.

And I added support for the proxy CA bundle: https://github.com/rpm-software-management/librepo/pull/227
option `LRO_PROXY_SSLCACERT`
