### ISSUE TITLE
proxy squid + https

### ISSUE THREAD

**Issue by mamachine** [rpm-software-management/librepo#86]
When using a squid to connect to HTTPS, intermediate result can be : 
  HTTP/1.1 200 Connection established

Therefore, when installing a package via dnf using a proxy on HTTPS, dnf fails with the message : 
  Interrupted by header callback: Server reports Content-Length: ....but expected size is: ........

I managed to get it work with the following patch : 
  [librepo_squid_https.txt](https://github.com/rpm-software-management/librepo/files/302746/librepo_squid_https.txt)

**Comment by Tojaj** [comment]
Thanks for report!
I wasn't sure if there couldn't be more different 200 messages other than ``OK`` that could be actually fine to accept, so instead of searching for ``OK`` I'm explicitly searching for 200 message with ``Connection established`` status and ignoring it.
