### ISSUE TITLE
[Debian] Python test 2/2 fails

### ISSUE THREAD

**Issue by mdeguzis** [rpm-software-management/librepo#93]
Previously, this ran fine under Python2. This fails under Python3. Arch Linux users as well see this issue. Is there a dependency I am missing? Is there a log file that can be reviewed for the test? Was this fixed in master? [Here](https://github.com/rholy/librepo/commit/96457dc6a76418af0ea4f8c3405471710fd06b9d.patch) is how the patch was applied in a fork.
```
 ----------------------------------------------------------------------
 Ran 105 tests in 71.202s
 
 FAILED (errors=1)
2/2 Test #2: test_python ......................***Failed 71.64 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) = 72.84 sec
```

**Comment by Tojaj** [comment]
Hi,
could you please provide an exact name of the test who failed? Ideally please provide whole output from the test run.

You can run only Python 3 tests manually from a checkout dir with command like:

    $ PYTHONPATH=`readlink -f ./build/librepo/python/python3/` nosetests-3.5 -s -v tests/python/tests/

Note: replace ``nosetests-3.5`` with version you have actually installed and available (e.g. ``nosetests-3.4``).
