### ISSUE TITLE
Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)

### ISSUE THREAD

**Issue by DengkeDu** [rpm-software-management/librepo#96]
When I run: `cmake ..` , it throws: `Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)` , but I have install the curl.

**Comment by DengkeDu** [comment]
Sorry, I should install libcurl4-openssl-dev.

**Comment by seemethere** [comment]
For anyone experiencing this same error on Fedora use `libcurl-devel`

**Comment by plusplusjiajia** [comment]
Centos:
yum install libcurl-devel
