### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND

### ISSUE THREAD

**Issue by DengkeDu** [rpm-software-management/librepo#97]
Hi 
When I run `cmake ..`, it throws:

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CHECK_LIBRARY
    linked by target "test_main" in directory /home/wrsadmin/ddk_github/librepo/tests
-- Configuring incomplete, errors occurred!

How can I slove this?

**Comment by tsipa** [comment]
How did you solved this?
